[package]
name = "kolumn"
version = "1.0.0"
authors = ["Fredrik Larsson <nossralf@gmail.com>"]
license = "MIT"

[badges]
travis-ci = { repository = "nossralf/kvicksilver" }
appveyor = { repository = "nossralf/kvicksilver" }
[dependencies]
clap = "^2"
